services:
  gazebo:
    container_name: sas_ur_control_template_gazebo
    build:
      context: ../../
      dockerfile: docker/Dockerfile.Gazebo
    stop_signal: SIGINT
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
    privileged: true # Needed for some gpu configurations.
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    command: /bin/bash -c "
      export GZ_SIM_RESOURCE_PATH=$$GZ_SIM_RESOURCE_PATH:$$(ros2 pkg prefix sas_robot_driver_gazebo)/sdf/
      && ros2 run sas_robot_driver_gazebo setup_vendor.sh ur
      && cd $$(ros2 pkg prefix sas_robot_driver_gazebo --share)/sdf
      && (ros2 launch sas_robot_driver_gazebo robot_driver_server_launch.py name:=ur_sim_1 config_file:=$$(ros2 pkg prefix sas_ur_control_template --share)/config/config.yaml &)
      && (ros2 launch sas_robot_driver_gazebo object_server_launch.py config_file:=$$(ros2 pkg prefix sas_ur_control_template --share)/config/config.yaml &)
      && (ros2 launch sas_robot_driver_gazebo simulator_server_launch.py config_file:=$$(ros2 pkg prefix sas_ur_control_template --share)/config/config.yaml &)
      && gz sim ur3e_world.sdf"
