services:
  gazebo:
    container_name: sas_ur_control_template_gazebo
    build:
      context: ../../
      dockerfile: docker/Dockerfile.Gazebo
    stop_signal: SIGINT
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
    privileged: true # Needed for some gpu configurations.
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    command: /bin/bash -c "
      export GZ_SIM_RESOURCE_PATH=$$GZ_SIM_RESOURCE_PATH:$$(ros2 pkg prefix sas_robot_driver_gazebo)/sdf/
      && cd $$(ros2 pkg prefix sas_robot_driver_gazebo --share)/sdf
      && (ros2 launch sas_ur_control_template ur3e_robot_driver_launch.py &)
      && (ros2 launch sas_ur_control_template server_launch.py &)
      && gz sim ur3e_world.sdf"
