services:
  teleoperation:
    container_name: sas_ur_control_template_teleoperation
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 1m
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    privileged: true
    environment:
      - ROS_DOMAIN_ID
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/sas_ur_control_template_devel/src/sas_ur_control_template/scripts/fastrtps_profile.xml
      - DISPLAY
    network_mode: "host" # x server related
    stdin_open: true
    tty: true
    command: /bin/bash -c "
      ros2 launch sas_ur_control_template teleop_simulation_launch.py"

