services:
  sas_ur_control_template:
    build: https://github.com/MarinhoLab/sas_ur_control_template.git#main:.devel/sas_ur_control_template
    volumes:
      - sas-ur-control-template-repo-data:/root/sas_tutorial_workspace/src/sas_ur_control_template/
      - ../../../sas_operator_side_receiver/:/root/sas_tutorial_workspace/src/sas_operator_side_receiver/
    network_mode: "host" 
    environment:
      - ROS_DOMAIN_ID
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/sas_tutorial_workspace/src/sas_ur_control_template/.devel/scripts/fastrtps_profile.xml
    stdin_open: true
    tty: true
    command: /bin/bash 

volumes:
  sas-ur-control-template-repo-data:
