services:
  sas_ur_control_template:
    build: .
    volumes:
      - ../../../sas_operator_side_receiver/:/root/sas_tutorial_workspace/src/sas_operator_side_receiver/
      - ../../../sas_patient_side_manager/:/root/sas_tutorial_workspace/src/sas_patient_side_manager/
      - ../../../sas_robot_kinematics_constrained_multiarm/:/root/sas_tutorial_workspace/src/sas_robot_kinematics_constrained_multiarm/
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    privileged: true
    environment:
      - ROS_DOMAIN_ID
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/sas_tutorial_workspace/src/sas_ur_control_template/.devel/scripts/fastrtps_profile.xml
      - DISPLAY
    network_mode: "host" # x server related
    stdin_open: true
    tty: true
    command: /bin/bash


