FROM ghcr.io/marinholab/gazebo:jazzy
LABEL authors="murilomarinho"
SHELL ["/bin/bash", "-c"]
ENV BASH_ENV="/etc/bash_env"

RUN curl -s --compressed "https://smartarmstack.github.io/smart_arm_stack_ROS2/KEY.gpg" \
| gpg --dearmor \
| sudo tee /etc/apt/trusted.gpg.d/smartarmstack_lgpl.gpg >/dev/null
RUN sudo curl -s --compressed -o /etc/apt/sources.list.d/smartarmstack_lgpl.list \
"https://smartarmstack.github.io/smart_arm_stack_ROS2/smartarmstack_lgpl.list"
RUN sudo apt update
RUN sudo apt-get install ros-jazzy-sas-*

RUN sudo apt-get update && sudo apt-get upgrade -y
RUN python3 -m pip install --upgrade dqrobotics --break-system-packages
RUN mkdir -p /root/sas_ur_control_template_devel/src
COPY . /root/sas_ur_control_template_devel/src/sas_ur_control_template
WORKDIR /root/sas_ur_control_template_devel
RUN colcon build
RUN echo "source /root/sas_ur_control_template_devel/install/setup.bash" > /etc/bash_env