services:
  robot:
    container_name: sas_ur_control_template_robot
    image: murilomarinho/sas:jazzy
    stop_signal: SIGINT
    stop_grace_period: 1m
    network_mode: "host" # Reverse connection with UR robot
    environment:
      - ROS_DOMAIN_ID
    cap_add:
      - SYS_NICE # PREEMPT_RT
    ulimits:
      rtprio: 99 # PREEMPT_RT
      rttime: -1 # PREEMPT_RT
    command: /bin/bash -c "
      cd /root/sas_ur_control_template_devel/docker/scripts
      && chmod +x prepare_robot_demo.sh
      && . ./prepare_robot_demo.sh
      && ros2 launch sas_robot_driver_ur robot_launch.py"
