services:
  sas_ur_control_template:
    image: murilomarinho/sas_ur_control_template:latest
    hostname: sas_ur_control_template_docker
    networks:
      - ros2-net
    command: /bin/bash -c "
      cd /root/sas_tutorial_workspace/src/sas_ur_control_template \
      && git pull \
      && cd /root/sas_tutorial_workspace \
      && colcon build \
      && cd /root/sas_tutorial_workspace/src/sas_ur_control_template/.devel/scripts/ \
      && ./countdown.sh 10\
      && ros2 launch sas_ur_control_template \
      real_robot_move_example_launch.py"

networks:
  ros2-net:
      driver: bridge

