services:
  sas_ur_control_template:
    image: murilomarinho/sas_ur_control_template:latest
    hostname: sas_ur_control_template_docker
    privileged: true
    stop_signal: SIGINT
    stop_grace_period: 1m
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1 # corresponds to 'unlimited'
    networks:
      - ros2-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #  memlock: 8428281856
    command: /bin/bash -c "
      cd /root/sas_tutorial_workspace/src/sas_ur_control_template \
       && cat /etc/bash_env \
      && git pull \
      && cd /root/sas_tutorial_workspace \
      && colcon build \
      && source install/setup.bash \
      && cd /root/sas_tutorial_workspace/src/sas_ur_control_template/.devel/scripts/ \
      && ./countdown.sh 3\
      && ros2 launch sas_ur_control_template \
      real_robot_move_example_launch.py"

  ros2_inspector:
    image: murilomarinho/sas:latest
    hostname: ros2_inspector
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
     - ros2-net

networks:
  ros2-net:
      driver: bridge
