services:
  sas_ur_control_template:
    build: ../sas_ur_control_template
    hostname: sas_ur_control_template_docker
    networks:
      - ros2-net
    volumes:
      - repo-data:/root/sas_tutorial_workspace/src/sas_ur_control_template/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /bin/bash -c "
      sleep 10
      && ros2 launch sas_ur_control_template \
      dummy_move_in_coppeliasim_example_cpp_launch.py \
      vrep_ip:='host.docker.internal' "

  coppeliasim:
    image: murilomarinho/coppeliasim:noble_470rev4
    hostname: coppeliasim_docker
    platform: linux/amd64
    environment:
      DISPLAY: $DISPLAY # x server related
    privileged: true # Needed for some gpu configurations.
    volumes:
      - repo-data:/root/sas_tutorial_workspace/src/sas_ur_control_template/
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    network_mode: "host" # x server related
    command: /bin/bash -c "
      cd /root/sas_tutorial_workspace/src/sas_ur_control_template/.devel/scripts
      && chmod +x run_simulation.sh
      && . ./run_simulation.sh "

networks:
  ros2-net:
      driver: bridge

volumes:
  repo-data:
