services:
  sas_ur_control_template:
    build: https://github.com/MarinhoLab/sas_ur_control_template.git#main:.devel/sas_ur_control_template
    volumes:
      - sas-ur-control-template-repo-data:/root/sas_tutorial_workspace/src/sas_ur_control_template/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /bin/bash -c "
      ros2 launch sas_ur_control_template \
      simulation_example_cpp_launch.py \
      ip:='host.docker.internal' \
      timeout:=10000"

  coppeliasim:
    image: murilomarinho/coppeliasim:noble_470rev4
    platform: linux/amd64
    stop_signal: SIGINT
    environment:
      DISPLAY: $DISPLAY # x server related
    privileged: true # Needed for some gpu configurations.
    volumes:
      - sas-ur-control-template-repo-data:/root/sas_tutorial_workspace/src/sas_ur_control_template/
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    network_mode: "host" # x server related
    command: /bin/bash -c "
      cd "$$COPPELIASIM_PATH"
      && ./coppeliaSim.sh \
      -s0 \
      /root/sas_tutorial_workspace/src/sas_ur_control_template/scenes/UR3e_480rev0.ttt"

volumes:
  sas-ur-control-template-repo-data:
