services:
  sas_ur_control_template:
    image: murilomarinho/sas_ur_control_template:latest
    hostname: sas_ur_control_template_docker
    networks:
      - ros2-net
    volumes:
      - repo-data:/root/sas_tutorial_workspace/src/sas_ur_control_template/
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  coppeliasim:
    image: murilomarinho/coppeliasim:noble_470rev4
    hostname: coppeliasim_docker
    platform: linux/amd64
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - repo-data:/root/sas_tutorial_workspace/src/sas_ur_control_template/
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    network_mode: "host" # Otherwise xserver can't be forwarded
    entrypoint: ["bash","-c","/root/sas_tutorial_workspace/src/sas_ur_control_template/.devel/scripts/run_simulation.sh"]
    stdin_open: true
    tty: true

networks:
  ros2-net:
      driver: bridge

volumes:
  repo-data: